name: Publish gem
description: Build and publish a Ruby gem
author: dawidd6
branding:
  icon: upload-cloud
  color: red
inputs:
  api_key:
    description: Rubygems.org API key
    required: true
runs:
  using: composite
  steps:
    - run: $GITHUB_ACTION_PATH/main.rb
      shell: bash
      env:
        API_KEY: ${{inputs.api_key}}
