name: Publish gem
description: Build and publish a Ruby gem
author: dawidd6
branding:
  icon: upload-cloud
  color: red
inputs:
  api_key:
    description: Rubygems.org API key
    required: true
runs:
  using: docker
  image: Dockerfile
